export const DESTINATION_ROUTES = [
  { country: 'japan', cities: ['osaka', 'tokyo', 'kyoto'] },
  { country: 'thailand', cities: ['bangkok', 'chiangmai', 'phuket'] },
  { country: 'singapore', cities: ['singapore'] },
  { country: 'vietnam', cities: ['danang', 'hanoi', 'hochiminh'] },
  { country: 'taiwan', cities: ['taipei', 'kaohsiung'] },
  { country: 'usa', cities: ['guam', 'hawaii', 'newyork'] },
  { country: 'philippines', cities: ['cebu', 'boracay', 'manila'] },
  { country: 'france', cities: ['paris'] },
  { country: 'italy', cities: ['rome', 'milano', 'venice'] },
  { country: 'australia', cities: ['sydney', 'melbourne', 'brisbane'] },
  { country: 'new-zealand', cities: ['auckland', 'queenstown', 'wellington'] },
  { country: 'canada', cities: ['vancouver', 'toronto', 'montreal'] },
  { country: 'united-kingdom', cities: ['london', 'edinburgh', 'manchester'] },
  { country: 'spain', cities: ['barcelona', 'madrid', 'seville'] },
  { country: 'germany', cities: ['berlin', 'munich', 'frankfurt'] },
  { country: 'indonesia', cities: ['bali', 'jakarta', 'yogyakarta'] },
  { country: 'hong-kong', cities: ['hong-kong'] },
  { country: 'netherlands', cities: ['amsterdam', 'rotterdam', 'the-hague'] },
  { country: 'portugal', cities: ['lisbon', 'porto', 'faro'] },
  { country: 'malaysia', cities: ['kuala-lumpur', 'penang', 'kota-kinabalu'] },
  { country: 'china', cities: ['beijing', 'shanghai', 'guangzhou'] },
  { country: 'united-arab-emirates', cities: ['dubai', 'abu-dhabi'] },
  { country: 'switzerland', cities: ['zurich', 'lucerne', 'interlaken'] },
  { country: 'austria', cities: ['vienna', 'salzburg', 'innsbruck'] },
  { country: 'czechia', cities: ['prague', 'cesky-krumlov', 'brno'] },
  { country: 'hungary', cities: ['budapest', 'szeged'] },
  { country: 'greece', cities: ['athens', 'santorini', 'thessaloniki'] },
  { country: 'turkey', cities: ['istanbul', 'cappadocia', 'antalya'] },
  { country: 'mexico', cities: ['mexico-city', 'cancun', 'los-cabos'] },
  { country: 'maldives', cities: ['male', 'maafushi'] },
  { country: 'croatia', cities: ['zagreb', 'dubrovnik', 'split'] },
] as const;