export const DESTINATION_ROUTES = [
  { country: 'japan', cities: ['osaka', 'tokyo', 'kyoto'] },
  { country: 'thailand', cities: ['bangkok', 'chiangmai', 'phuket'] },
  { country: 'singapore', cities: ['singapore'] },
  { country: 'vietnam', cities: ['danang', 'hanoi', 'hochiminh'] },
  { country: 'taiwan', cities: ['taipei', 'kaohsiung'] },
  { country: 'usa', cities: ['guam', 'hawaii', 'newyork'] },
  { country: 'philippines', cities: ['cebu', 'boracay', 'manila'] },
  { country: 'france', cities: ['paris'] },
  { country: 'italy', cities: ['rome', 'milano', 'venice'] },
  { country: 'australia', cities: ['sydney', 'melbourne', 'brisbane'] },
  { country: 'new-zealand', cities: ['auckland', 'queenstown', 'wellington'] },
  { country: 'canada', cities: ['vancouver', 'toronto', 'montreal'] },
  { country: 'united-kingdom', cities: ['london', 'edinburgh', 'manchester'] },
  { country: 'spain', cities: ['barcelona', 'madrid', 'seville'] },
  { country: 'germany', cities: ['berlin', 'munich', 'frankfurt'] },
  { country: 'indonesia', cities: ['bali', 'jakarta', 'yogyakarta'] },
  { country: 'hong-kong', cities: ['hong-kong'] },
  { country: 'netherlands', cities: ['amsterdam', 'rotterdam', 'the-hague'] },
  { country: 'portugal', cities: ['lisbon', 'porto', 'faro'] },
] as const;