CREATE TYPE "EvidenceLevel" AS ENUM ('OFFICIAL', 'CORROBORATED', 'COMMUNITY_SIGNAL');
CREATE TYPE "SourceKind" AS ENUM ('OFFICIAL', 'GOVERNMENT_ADVISORY', 'COMMUNITY', 'WIKI', 'EDITORIAL');

ALTER TABLE "Warning"
  ADD COLUMN "evidenceLevel" "EvidenceLevel" NOT NULL DEFAULT 'OFFICIAL',
  ADD COLUMN "contextNotes" TEXT,
  ADD COLUMN "sideEffects" TEXT,
  ADD COLUMN "counterpoint" TEXT,
  ADD COLUMN "independentSourceCount" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Source"
  ADD COLUMN "kind" "SourceKind" NOT NULL DEFAULT 'OFFICIAL',
  ADD COLUMN "platform" TEXT;